name: Snake animation

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow svgwrite requests
      - name: Run snake generator
        run: python ./generate.py
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Aashrya Shrivastava
          author_email: aashryashrivastava@gmail.com
          message: "Update README with snake animation"
          add: README.md
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
